In [1]:
import pandas as pd
import numpy as np

In [14]:
df_train = pd.read_csv("train_co.csv",index_col=False)
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
2,0,73,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
3,0,0,0,0,0,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,10
4,0,0,0,0,0,0,0,0,18,255,...,0,0,0,0,0,0,0,0,0,10

In [15]:
labels=df_train["784"]

In [16]:
df_train.drop(df_train.columns[[784]],axis=1,inplace=True)
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,73,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,18,255,...,0,0,0,0,0,0,0,0,0,0

In [17]:
np.random.seed(1212)
import keras
from keras.models import Model
from keras.layers import *
from keras import optimizers
from keras.layers.convolutional import Conv2D, MaxPooling2D 
from keras.models import Sequential
from keras.utils import np_utils

In [18]:
labels=np.array(labels)

In [19]:
from keras.utils.np_utils import to_categorical
cat = to_categorical(labels,num_classes=13)

In [20]:
l=[]
for i in range(7567):
    l.append(np.array(df_train[i:i+1]).reshape(28,28,1))

In [21]:
np.random.seed(7)

In [22]:
model=Sequential()
model.add(Conv2D(512,(5,5),input_shape=(28,28,1),activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(256,(3,3),input_shape=(28,28,1),activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(128,(3,3),input_shape=(28,28,1),activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128,activation="relu"))
model.add(Dense(64,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dense(13,activation="softmax"))

In [23]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d_4 (Conv2D)            (None, 24, 24, 512)       13312
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 12, 12, 512)       0
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 10, 10, 256)       1179904
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 5, 5, 256)         0
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 3, 3, 128)         295040
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 1, 1, 128)         0
_________________________________________________________________
dropout_2 (Dropout)          (None, 1, 1, 128)         0
_________________________________________________________________
flatten_2 (Flatten)          (None, 128)               0
_________________________________________________________________
dense_5 (Dense)              (None, 128)               16512
_________________________________________________________________
dense_6 (Dense)              (None, 64)                8256
_________________________________________________________________
dense_7 (Dense)              (None, 32)                2080
_________________________________________________________________
dense_8 (Dense)              (None, 13)                429
=================================================================
Total params: 1,515,533
Trainable params: 1,515,533
Non-trainable params: 0
_________________________________________________________________

In [24]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [26]:
model.fit(np.array(l),cat,shuffle=True,epochs=10)

Epoch 1/10
7567/7567 [==============================] - 84s 11ms/step - loss: 0.4510 - accuracy: 0.8694
Epoch 2/10
7567/7567 [==============================] - 84s 11ms/step - loss: 0.2894 - accuracy: 0.9148
Epoch 3/10
7567/7567 [==============================] - 83s 11ms/step - loss: 0.2135 - accuracy: 0.9417
Epoch 4/10
7567/7567 [==============================] - 85s 11ms/step - loss: 0.1863 - accuracy: 0.9463
Epoch 5/10
7567/7567 [==============================] - 84s 11ms/step - loss: 0.1690 - accuracy: 0.9512
Epoch 6/10
7567/7567 [==============================] - 84s 11ms/step - loss: 0.1299 - accuracy: 0.9625
Epoch 7/10
7567/7567 [==============================] - 85s 11ms/step - loss: 0.1200 - accuracy: 0.9652
Epoch 8/10
7567/7567 [==============================] - 84s 11ms/step - loss: 0.1334 - accuracy: 0.9621
Epoch 9/10
7567/7567 [==============================] - 83s 11ms/step - loss: 0.0902 - accuracy: 0.9745
Epoch 10/10
7567/7567 [==============================] - 83s 11ms/step - loss: 0.0861 - accuracy: 0.9732

In [41]:
import cv2
img=cv2.imread("C:/Users/Anmol Pabla/Documents/Data1/hi.png",cv2.IMREAD_GRAYSCALE)
cv2.imshow("w",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
if img is not None:
    img=~img
    _, thresh=cv2.threshold(img,127,255,cv2.THRESH_BINARY)
    ctrs,_=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    cnt=sorted(ctrs,key=lambda ctr:cv2.boundingRect(ctr)[0])
    w=int(28)
    h=int(28)
    train_data=[]
    rects=[]
    for c in cnt:
        x,y,w,h = cv2.boundingRect(c)
        rect=[x,y,w,h]
        rects.append(rect)
    print("rects",rects)    
    bool_rect=[]
    for r in rects:
        l=[]
        for rec in rects:
            flag=0
            if rec!=r:
                if r[0]<(rec[0]+rec[2]+10) and rec[0]<(r[0]+r[2]+10) and r[1]<(rec[1]+rec[3]+10) and rec[1]<(r[1]+r[3]+10):
                    flag=1
                l.append(flag)
            if rec==r:
                l.append(0)
        bool_rect.append(l)
    print("bools",bool_rect)        
    dump_rect=[]
    for i in range(0,len(cnt)):
        for j in range(0,len(cnt)):
            if bool_rect[i][j]==1:
                area1 = rects[i][2]*rects[i][3]
                area2 = rects[j][2]*rects[j][3]
                if(area1==min(area1,area2)):
                    dump_rect.append(rects[i])
    print("dump",dump_rect)
    final_rect = [i for i in rects if i not in dump_rect]
    print("final", final_rect)
    for r in final_rect:
        x=r[0]
        y=r[1]
        w=r[2]
        h=r[3]
        im_crop=thresh[y:y+h+10,x:x+w+10]
        im_resize=cv2.resize(im_crop,(28,28))
        cv2.imshow("work",im_resize)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        train_data.append(im_resize)

rects [[34, 237, 169, 205], [242, 220, 242, 217], [599, 205, 201, 261], [870, 205, 141, 267], [882, 363, 121, 101]]
bools [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 1, 0]]
dump [[882, 363, 121, 101]]
final [[34, 237, 169, 205], [242, 220, 242, 217], [599, 205, 201, 261], [870, 205, 141, 267]]

In [42]:
s=""
for i in range(len(train_data)):
    train_data[i]=np.array(train_data[i])
    train_data[i]=train_data[i].reshape(1,28,28,1)
    result=model.predict_classes(train_data[i])
    if (result[0]==0):
        s+='0'
    if (result[0]==1):
        s+='1'
    if (result[0]==2):
        s+='2'
    if (result[0]==3):
        s+='3'
    if (result[0]==4):
        s+='4'    
    if (result[0]==5):
        s+='5'    
    if (result[0]==6):
        s+='6'
    if (result[0]==7):
        s+='7'
    if (result[0]==8):
        s+='8'
    if (result[0]==9):
        s+='9'
    if (result[0]==10):
        s+='-'
    if (result[0]==11):
        s+='+'    
    if (result[0]==12):
        s+='*'
if(s[-1]=='+'): s = s[:-1] + '4'      
if(s[0]== '+'): s = '4' + s[1:]          
print(s)

1+*6

In [37]:
eval(s)

24